### ISSUE TITLE
Implement tracking of ShapeLearningEvents [2-4h]

### ISSUE THREAD

**Issue by nya-elimu** [literacyapp-org/shapi#25]
- [x] Import Gradle library
- [x] Report learning events using the `EventTracker` class

**Comment by jo-elimu** [comment]
@tbarthel-fr @vbarthel-fr See https://github.com/literacyapp-org/literacyapp-analytics/tree/master/eventtracker

**Comment by vbarthel-fr** [comment]
@jogrimst the event tracker library has a min sdk version set to 21, but the current min sdk of the shapi app is 16.
https://github.com/literacyapp-org/literacyapp-analytics/blob/master/eventtracker/build.gradle#L8

Correct me if I'm wrong, but I think that the event tracker library does not use any features requiring lolllipop. So we have to options:

- bump the min sdk version of the app to 21
- ignore the min sdk version of the event tracker library and stick to a min sdk version of 16.

Do you have a preference? =)

**Comment by vbarthel-fr** [comment]
Here is a commit implementing the event tracker and using the option 2 (ignoring the min sdk of the library)

https://github.com/literacyapp-org/shapi/commit/0bb099355aa6a55e33e58daedb391bac95c1defa

If it's OK for you, I will submit a PR =)

**Comment by jo-elimu** [comment]
@vbarthel-fr All the other apps on our platform use min SDK 21. So could you increase from 16 to 21 as well?

We currently do not support tablets running older APIs than 21: http://literacyapp.org/publish

**Comment by vbarthel-fr** [comment]
OK, I will bump the min sdk =)

PR incoming !

**Comment by vbarthel-fr** [comment]
Merged on dev, closing the issue!
