### ISSUE TITLE
Pressing a box causes shape to disappear [2-4h]

### ISSUE THREAD

**Issue by jo-elimu** [literacyapp-org/shapi#39]
When pressing one of the 4 boxes, the shape in the box disappeared and the "error" audio played. Similarly, when pressing a box with the correct answer, the shape disappeared and the "correct" audio played.

![screenshot_20170609-165810](https://user-images.githubusercontent.com/1451036/26978767-f20bd9ca-4d2c-11e7-97f7-b921add2bdac.png)

**Comment by vbarthel-fr** [comment]
Here is the root of the "problem": https://github.com/literacyapp-org/shapi/issues/35

**Comment by vbarthel-fr** [comment]
Should be fixed!
